<div class="jumbotron">
    <h1>Lab 3</h1>
    <small>by Karina Ramirez A00923169</small>
</div>

<div class="container">
    <div class="row col-6">

        <!-- form -->
        <form action="/" method="POST">

                <label for="exampleInputPassword1">Username</label>
                <input type="text" class="form-control" id="username" placeholder="Username">
                <label>Email</label>
                <input type="text" class="form-control" id="email" placeholder="Email address">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                <br>
                <label>Age</label>
                <input type="text" class="form-control" id="age" aria-describedby="ageHelp" placeholder="Age">
            
            <button type="submit" class="btn btn-primary">Submit</button>
            
        </form>

        <p>
    <?php
    //echo phpinfo();  
    echo $this->message;
    ?>

    </p>
    </div>  
</div>

