<div class="container">
    <div class="row col-6">
        
    <h2>
    <?php
    if(isset( $this->name)) {
        echo 'Hi '.$this->name;
    }

    if(isset( $this->error)) {
        echo '<div class="alert alert-danger" role="alert">'.$this->error.'</div>';
    }

    if(isset( $this->message)) {
        echo $this->message; // just gonna be blank
    }

    ?>
    </h2>

    </div>  
</div>

