<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center  brown-text text-lighten-2">Welcome to Page 2</h1>
        <div class="row center">
          <h5 class="header col s12 light">Have some cute pictures</h5>
        </div>
        
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="/img/poordino.png" alt="Poor dino"></div>
  </div>


  <div class="container grey lighten-2">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">android</i></h2>
            <h5 class="center">Lorem ipsum</h5>

            <p class="light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porta sem vitae nisl tristique viverra. Nam sed commodo nibh, vel auctor nisl. Sed ut justo vulputate, efficitur augue eu, bibendum odio. Maecenas vitae vestibulum lorem. </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">announcement</i></h2>
            <h5 class="center">Ocri varius</h5>

            <p class="light">Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis nisl lectus, porttitor venenatis elit sed, fermentum elementum eros. Pellentesque lobortis porta quam eget rutrum.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">album</i></h2>
            <h5 class="center">Nullam nulla</h5>

            <p class="light">Nullam nulla erat, rutrum id feugiat eget, dapibus vel nisl. Cras gravida est vel libero luctus egestas. Maecenas sagittis, mauris in tincidunt dapibus, arcu augue congue nulla, vitae vulputate neque justo eget lorem. Morbi quis nulla leo.

</p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <!--<h5 class="header center bold s14 green-text text-darken-2">I'm hungry.</h5>-->
        </div>
      </div>
    </div>
    <div class="parallax"><img src="/img/befood.jpg" alt="Be Food wallpaper"></div>
  </div>

  <div class="container grey lighten-2">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Lorem ipsum</h4>
          <p class="left-align light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat.</p>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <!--<h5 class="header col s14 brown-text center">I finished this at 4am.</h5>-->
        </div>
      </div>
    </div>
    <div class="parallax"><img src="/img/thereforeeat.jpg" alt="Therefore Eat wallpaper"></div>
  </div>

  <footer class="page-footer brown lighten-2">
    <div class="container">
      <div class="row">
        <div class="col s12">
          <h5 class="white-text">Cute things are great</h5>
          <p class="grey-text text-lighten-4">Lorem ipsum something something something I'm so hungry oh my god.</p>


        </div>
        
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>